#nixpacks.toml
[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd="gunicorn app:app"
