#nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc", "ffmpeg", "cudatoolkit"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd="gunicorn app:app"
